### ISSUE TITLE
This is feature not Issue

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry-community/mongodb-bosh-release#11]
Hi everyone, is any have mongoDB broker to create service in cloud foundry market place.

**Comment by linlynn** [comment]
@abhilash07  We do have   @huangered

**Comment by abhilash07** [comment]
hi lynn lin thanks for your response but i didn't see and broker
registration ot broker package in this release. If possible can you please
explain how to create service in cf marketplace using this release.

**Comment by linlynn** [comment]
It is still in our private repository:) we will do some clean up then put here

**Comment by abhilash07** [comment]
hi lynn lin thanks for your kindness, hope to see future. Have a good
weekend

**Comment by axelfauvel** [comment]
That's great news :)
