### ISSUE TITLE
Merge haproxy.ip and haproxy.mongodb.ip in 1 property

### ISSUE THREAD

**Issue by axelfauvel** [cloudfoundry-community/mongodb-bosh-release#4]
Hey guys,

Thanks for your work on mongoDB, it's awesome :)

After deploying your release, i got to the point that `haproxy.ip` and `haproxy.mongodb.ip` are the same thing. Am i missing something ?

If not it could be nice to merge these properties in `haproxy.ip`

I can handle that if you want.

best

**Comment by linlynn** [comment]
go ahead @axelfauvel   thanks!!

**Comment by axelfauvel** [comment]
done in https://github.com/cloudfoundry-community/mongodb-bosh-release/pull/6
